server:
  port: 8081

spring:
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://47.93.232.108:3306/WN?characterEncodeing=utf-8
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: root
      #配置监控拦截的filters
      filters: stat,wall
      #最大活跃数
      maxActive: 20
      #初始化数量
      initialSize: 1
      #最大连接等待超时时间
      maxWait: 60000
      #打开PSCache,并指定大小
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false

#      druid:
#        web-stat-filter:
#          enabled: true
#          url-pattern: /*
#          exclusions: /*.js,/*.gif,/*.jpg,/*.png,/*.css,/*.ico,/druid/*
#          session-stat-enable: false
#          session-stat-max-count: 1000
#        stat-view-servlet:
#          allow: 127.0.0.1
#          login-username: druid
#          login-password: druid
#          reset-enable: false
#          url-pattern: /druid/*
  jpa:
    #显示sql
    show-sql: true
    format_sql: true

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
